version: '3.7'

services:

  currency-exchange:
    image: moro/mmv1-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network

  naming-server:
    image: moro/mmv1-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network  

networks:
  currency-network: